version: '3.8'

services:
  # AGNTCY Infrastructure Services - only SLIM is needed
  slim:
    image: ghcr.io/agntcy/slim:0.3.15
    container_name: slim
    ports:
      - "46357:46357"
    environment:
      - PASSWORD=${SLIM_GATEWAY_PASSWORD:-dummy_password}
      - CONFIG_PATH=/config.yaml
    volumes:
      - ./config/docker/slim/server-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:46357/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Orbit Agent Services
  ear-to-ground:
    build:
      context: .
      dockerfile: docker/Dockerfile.ear-to-ground
    platform: linux/amd64
    ports:
      - "9001:9001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLIM_BROKER_URL=http://slim:46357
      - ORBIT_TWEET_FILE=/app/data/tweets_astronomer.json
      - AGENT_PORT=9001
    volumes:
      - ./data:/app/data:ro
      - ./:/app:cached
    depends_on:
      - slim
    restart: unless-stopped
    command: >
      sh -c "watchfiles --filter python 'python -m agents.ear_to_ground.server' /app"

  sentiment-analyst:
    build:
      context: .
      dockerfile: docker/Dockerfile.sentiment-analyst
    platform: linux/amd64
    ports:
      - "9002:9002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLIM_BROKER_URL=http://slim:46357
      - AGENT_PORT=9002
    depends_on:
      - slim
    restart: unless-stopped

  risk-score:
    build:
      context: .
      dockerfile: docker/Dockerfile.risk-score
    platform: linux/amd64
    ports:
      - "9003:9003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLIM_BROKER_URL=http://slim:46357
      - CRISIS_THRESHOLD=${CRISIS_THRESHOLD:-70}
      - AGENT_PORT=9003
    depends_on:
      - slim
    restart: unless-stopped

  fact-checker:
    build:
      context: .
      dockerfile: docker/Dockerfile.fact-checker
    platform: linux/amd64
    ports:
      - "9004:9004"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLIM_BROKER_URL=http://slim:46357
      - AGENT_PORT=9004
    volumes:
      - ./data:/app/data:ro
    depends_on:
      - slim
    restart: unless-stopped

  legal-counsel:
    build:
      context: .
      dockerfile: docker/Dockerfile.legal-counsel
    platform: linux/amd64
    ports:
      - "9005:9005"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLIM_BROKER_URL=http://slim:46357
      - AGENT_PORT=9005
    volumes:
      - ./data:/app/data:ro
    depends_on:
      - slim
    restart: unless-stopped

  press-secretary:
    build:
      context: .
      dockerfile: docker/Dockerfile.press-secretary
    platform: linux/amd64
    ports:
      - "9006:9006"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLIM_BROKER_URL=http://slim:46357
      - AGENT_PORT=9006
    depends_on:
      - slim
    restart: unless-stopped


  # Gateway Service (FastAPI + React UI)
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    platform: linux/amd64
    ports:
      - "8000:8000"  # FastAPI
      - "5173:5173"  # Vite dev server
    environment:
      - SLIM_BROKER_URL=http://slim:46357
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8000
    depends_on:
      - slim
      - ear-to-ground
      - sentiment-analyst
      - risk-score
      - fact-checker
      - legal-counsel
      - press-secretary
    restart: unless-stopped

networks:
  default:
    name: orbit-network